# Generated by Django 2.2.8 on 2019-12-08 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('site_settings', '0003_hourssettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterCTASettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='We’ll take good care of you [and your car]', max_length=100)),
                ('subtitle', models.CharField(default='We’ll treat your vehicle as if it’s our own. And we’ve got high standards. Like, really high.', max_length=250)),
                ('button_text', models.CharField(default='Book an Appointment', max_length=25)),
                ('button_external_page', models.URLField(blank=True, help_text='If an internal page is selected, it will be used before the external page.')),
                ('button_internal_page', models.ForeignKey(blank=True, help_text='If an internal page is selected, it will be used before the external page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
