# Generated by Django 2.2.8 on 2019-12-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_footerctasettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerctasettings',
            name='button_text',
            field=models.CharField(default='Contact Us', max_length=25),
        ),
        migrations.AlterField(
            model_name='footerctasettings',
            name='subtitle',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='footerctasettings',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
